# Site Info
title: Dans Mind Space
tagline: 'A jekyll blog theme powered by bootstrap'
description: 'A jekyll blog theme powered by bootstrap </a>made by <a href="https://www.sharad.cf" target="_blank">@sharadcodes</a>.'
baseurl: '/'
url: http://dansmind.space
# permalink: /log/:year/:month/:day/:title

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM

# About/contact
author: Daniel Dahl

bio: Programmer / Thinker 
  
contact:
   - title: Github
     link:  https://github.com/dansmindspace

   - title: Gmail
     link:  mailto:dan.thelostsorcerer@gmail.com
  
skills:  
   - title: Python
     level: 69
     color: warning


# Navigation (2nd level links supported)

toc:
  - title: Home
    url: /
  - title: Project Logs
    url: /log/    
  - title: About
    url: /about
  - title: Author
    url: /author    
